spring:
  session:
    store-type: redis
  redis:
    port: 6379
zuul: 
  retryable: true
  routes:
    order-management-ms:
      path: /order-management/**
      sensitiveHeaders: Authorization, Set-Cookie

server:
    servlet:
        session:
            timeout: 30m